import type { Metadata, Viewport } from 'next'
import { IBM_Plex_Mono, IBM_Plex_Sans, Space_Grotesk } from 'next/font/google'
import './globals.css'

/**
 * Everything both root layouts share.
 *
 * There are two of them because `<html lang>` has to name the language of
 * the page it wraps, and a root layout in the App Router cannot see the
 * `[locale]` segment below it — so the English pages were served as
 * `lang="id"` and read aloud by an Indonesian synthesiser. The locale
 * layout is a root layout now, and the redirect at `/` has its own.
 *
 * Fonts, metadata and the base path live here so the two roots cannot
 * drift apart.
 */

/**
 * The three typefaces PRD §11 asks for, actually loaded.
 *
 * They were named in `globals.css` as CSS variables from the start but no
 * font was ever fetched or declared, so every one of them silently fell
 * through to `ui-sans-serif` — the whole app rendered in the system UI
 * face. `next/font` self-hosts them into the static export, so there is no
 * runtime request and no layout shift.
 *
 * Space Grotesk carries the counts: seeds per hole, seeds banked, scores.
 * Counts are the content here, so the display face is a numeral face
 * first and a heading face second.
 */
const display = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-display',
  display: 'swap',
})

const sans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-sans',
  display: 'swap',
})

/** Citations and connection codes — PRD §11. */
const mono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-mono',
  display: 'swap',
})

/** Kelas font untuk <html>, sama di kedua root. */
export const KELAS_FONT = `${display.variable} ${sans.variable} ${mono.variable}`

const JUDUL = 'Congklak — dengan aturan kedaerahan yang bersumber'
const RINGKAS =
  'Congklak / dakon dengan ruleset kedaerahan yang eksplisit, bersumber, dan bisa dipilih.'

/**
 * Static export under a basePath, so every asset path has to carry it —
 * Next does not rewrite the strings given to `metadata`. `BASE` is the same
 * value next.config.js hands the build.
 */
export const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

/**
 * Cache-buster for the tab icon.
 *
 * Browsers cache favicons far more stubbornly than ordinary assets, and
 * they key part of that cache to the origin — this app is a path on
 * andifathulms.github.io, which already serves a /favicon.ico of its own
 * for the portfolio. Anyone who opened the site before the icon existed
 * keeps being shown whatever was cached then, however correct the markup
 * is. Verified: the browser does request our SVG and gets 200, so the
 * markup was never the problem.
 *
 * Bumping this changes the URL, which is the only reliable way to make a
 * cached favicon let go. Raise it when the mark itself changes.
 */
const IKON_V = '2'

/**
 * Where the site actually lives. Only Open Graph needs it — those URLs have
 * to be absolute, and without a base Next resolves them against
 * `localhost:3000`, which is what a shared link would then point at.
 */
const ASAL = process.env.NEXT_PUBLIC_SITE_ORIGIN ?? 'https://andifathulms.github.io'

export const metadata: Metadata = {
  metadataBase: new URL(`${ASAL}${BASE}/`),
  title: JUDUL,
  description: RINGKAS,
  applicationName: 'Congklak',
  /**
   * Written by hand in `public/` rather than generated by `app/manifest.ts`:
   * the generated route emits its <link> without the basePath, which 404s on
   * Pages. Everything inside the file is relative to the manifest's own URL,
   * so the basePath never appears in it and renaming the repository cannot
   * break it.
   */
  manifest: `${BASE}/manifest.webmanifest`,
  icons: {
    // The SVG is the 4-seed small-size form of the mark; the 32px PNG is
    // there for anything that will not take an SVG.
    icon: [
      { url: `${BASE}/favicon.svg?v=${IKON_V}`, type: 'image/svg+xml' },
      { url: `${BASE}/favicon-32.png?v=${IKON_V}`, type: 'image/png', sizes: '32x32' },
    ],
    apple: { url: `${BASE}/apple-touch-icon.png?v=${IKON_V}`, sizes: '180x180' },
  },
  openGraph: {
    type: 'website',
    siteName: 'Congklak',
    title: JUDUL,
    description: RINGKAS,
    // Relative to metadataBase, which already carries the basePath —
    // prefixing it again produced /congklak/congklak/og.png.
    images: [{ url: 'og.png', width: 1200, height: 630 }],
  },
  twitter: { card: 'summary_large_image', images: ['og.png'] },
}

export const viewport: Viewport = {
  // The mat the board sits on, so the browser chrome meets the page rather
  // than framing it. Not the brand paper — this has to match what is
  // actually painted behind the content.
  themeColor: '#E4DDCD',
}
